# Generated by Django 5.0.1 on 2024-01-14 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_soha_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='reyting',
            options={'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='soha',
            options={'verbose_name_plural': 'Sohas'},
        ),
        migrations.RenameField(
            model_name='soha',
            old_name='question',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='reyting',
            name='result',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='base.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reyting',
            name='correct_answers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reyting',
            name='percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reyting',
            name='total_questions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
