# Generated by Django 5.0.1 on 2024-01-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_question_options_alter_reyting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soha',
            options={'verbose_name_plural': 'Soha'},
        ),
        migrations.AddField(
            model_name='reyting',
            name='soha',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='base.soha'),
            preserve_default=False,
        ),
    ]
